### ISSUE TITLE
Great little app - but no exit code

### ISSUE THREAD

**Issue by brettswift** [crdoconnor/commandlib#1]
This works well for my purpose where I need to parse output but not display it. 

However, It'd be nice to have a couple of features: 

1. display text that matches a filter
2. get the exit code  of a command. 

It doesn't seem like there's a way of getting the exit code.   That would be nice especially if you want to chain commands and inspect output as well as exit code.

**Comment by crdoconnor** [comment]
* You can get text output by using .output(). I'm not sure what you mean by text that matches a filter but you can probably do some sort of filtering on the string you get back.

* You can get exit code by catching CommandExitException as exception and then getting exception.exit_code.

Does that work for your purposes?

If not, if you show me your use case (ideally with some code) then I might be able to help further.

**Comment by brettswift** [comment]
Somewhat answers.  I have been using .output().   Handling that exception should work then. 

I'm using this: 
```
my_command = Command("run.sh").with_shell()
output = my_command.output()
```


What I mean by filtering - ultimately when I run `.output()` it's tough to get feedback to the user that the command is still running.  I only get the result at the end.   `run()` pipes to STDOUT so I see the command running, but I can't parse the output.   I'd like to have both configurable. 


The code right now does a recursive loop on .. I believe `self.piped.output()`.   I'm not sure of the pythonic way to attach an event listener so I can get the output as it happens instead of just at the end.  But maybe in the recursive call it could fire off a listener that you could allow a user to inject. (maybe there's a better way?)

If I were to pseudo code the user experience, it might look something like this. 
```
command = Command("long_running.sh").with_shell()

def on_listen(output):
    print("output from commandlib: " + output)
   
command.output_listener = on_listen

all_output = command.output()
```

That would print all the output to the screen,  AND give me the full output at the end of the run.  Does that give you an idea of what I was getting at?  Maybe it's already possible..  that code was meant to describe the behaviour I was trying to get - not to suggest how to write the code.

The filter I referred to could be on the listener.   Something like 

`command.output_listener(on_listen, filter_regex='^Failed:.+$')`  

to only print failed statements. 

Does that help?

**Comment by crdoconnor** [comment]
Ah i see - you want to interact with the process once it is running. commandlib explicitly won't do that - it *only* runs the command until it has finished and then returns the output. However, it contains hooks to two libraries that specialize in that - icommandlib and pexpect.

Details are here: https://github.com/crdoconnor/commandlib/blob/master/hitch/icommand-or-pexpect.story

icommandlib is still somewhat alpha-ish but if you look at the .story files in this directory it should give you some idea of what it can do: https://github.com/crdoconnor/icommandlib/tree/master/hitch
